name: Build Docker image
description: Build, and optionally push, a Docker image

inputs:
  project:
    description: Project name
  push:
    description: Whether to push images to the registry
    default: 'false'
  force-deploy:
    description: Forces tagging and deploying of image
    default: 'false'
  version:
    description: Version

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v2
      if: contains(fromJSON(steps.check-changes.outputs.projects), inputs.project) || inputs.force-deploy == 'true'
    - uses: docker/setup-buildx-action@v2
      if: contains(fromJSON(steps.check-changes.outputs.projects), inputs.project) || inputs.force-deploy == 'true'
    - uses: docker/login-action@v2
      if: contains(fromJSON(steps.check-changes.outputs.projects), inputs.project) || inputs.force-deploy == 'true'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker images
      uses: docker/build-push-action@v4
      if: inputs.force-deploy == 'true'
      with:
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/ministryofjustice/${{ inputs.project }}:latest
          ghcr.io/ministryofjustice/${{ inputs.project }}:${{ inputs.version }}
