---
# Per environment values which override defaults in hmpps-health-ping/values.yaml

generic-service:
  env:
    REFRESH_INTERVAL: "180"
    REDIS_MAX_STREAM_LENGTH: 1440
    LOG_LEVEL: info

  ingress:
    host: hmpps-health-ping.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-prod
