---
# Per environment values which override defaults in hmpps-health-ping/values.yaml

generic-service:
  env:
    REFRESH_INTERVAL: "180"
    REDIS_MAX_STREAM_LENGTH: 360
    LOG_LEVEL: debug

  ingress:
    host: hmpps-health-ping-dev.hmpps.service.justice.gov.uk

  namespace_secrets:
    hmpps-health-ping:
      SERVICE_CATALOGUE_FILTER: "SERVICE_CATALOGUE_FILTER"

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod
