---
# Per environment values which override defaults in hmpps-health-ping/values.yaml

generic-service:
  env:
    REFRESH_INTERVAL: "180"
    REDIS_MAX_STREAM_LENGTH: 1440
    LOG_LEVEL: info

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts
