---
# Per environment values which override defaults in hmpps-health-ping/values.yaml

generic-service:
  env:
    REFRESH_INTERVAL: "180"
    REDIS_MAX_STREAM_LENGTH: 360
    LOG_LEVEL: info

  ingress:
    host: hmpps-health-ping-dev.hmpps.service.justice.gov.uk

  namespace_secrets:
    hmpps-health-ping:
      SERVICE_CATALOGUE_FILTER: "SERVICE_CATALOGUE_FILTER"
    hmpps-envoy-https-proxy-env:
      HTTP_PROXY: "HTTP_PROXY"
      HTTPS_PROXY: "HTTPS_PROXY"
      NO_PROXY: "NO_PROXY"
      http_proxy: "HTTP_PROXY"
      https_proxy: "HTTPS_PROXY"
      no_proxy: "NO_PROXY"

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod
