---
generic-service:
  nameOverride: hmpps-health-ping

  replicaCount: 1

  image:
    repository: ghcr.io/ministryofjustice/hmpps-health-ping
    tag: xxx    # override at deployment time
    port: 3000

  ingress:
    enabled: false

  # Due to a bug cant disable/override the sub chart.
  # https://github.com/helm/helm/pull/12162
  #livenessProbe: null
  livenessProbe:
    exec:
      command:
      - test
      - "true"
  #readinessProbe: null
  readinessProbe:
    exec:
      command:
      - test
      - "true"

  # Environment variables to load into the deployment
  env:
    REFRESH_INTERVAL: "180"
    REDIS_TLS_ENABLED: "true"
    REDIS_PORT: 6379
    REDIS_MAX_STREAM_LENGTH: 360
    LOG_LEVEL: debug

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-health-ping:
      SERVICE_CATALOGUE_API_ENDPOINT: "SERVICE_CATALOGUE_API_ENDPOINT"
      SERVICE_CATALOGUE_API_KEY: "SERVICE_CATALOGUE_API_KEY"
    elasticache-redis:
      REDIS_ENDPOINT: "primary_endpoint_address"
      REDIS_TOKEN: "auth_token"

generic-prometheus-alerts:
  targetApplication: hmpps-health-ping
