name: Pipeline

on:
  push:
    branches:
      - init-project
  workflow_dispatch: # Can be triggered manually from a branch

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      push: true
    secrets: inherit
